knp_paginator:
    page_range: 5          # number of links shown in the pagination menu
    default_options:
        page_name: page    # page query parameter name
        sort_field_name: sort
        sort_direction_name: direction
        distinct: true
    template:
        pagination: '@KnpPaginator/Pagination/bootstrap_v5_pagination.html.twig' 